//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastfoodManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string FullName { get; set; }
        public string Sex { get; set; }
        public string DoB { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Addr { get; set; }
        public int Auth { get; set; }
    }
}
