//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastfoodManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int BillNumber { get; set; }
        public string BillDate { get; set; }
        public int Total { get; set; }
        public string OrderID { get; set; }
        public string StaffID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
    }
}
