//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastfoodManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT
    {
        public string TicketID { get; set; }
        public string AdminID { get; set; }
        public string ImportDate { get; set; }
        public string Name { get; set; }
        public int UnitPrice { get; set; }
        public int Quantity { get; set; }
    }
}
