//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastfoodManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTSTORAGE
    {
        public string IngID { get; set; }
        public string IngName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> IngStatus { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
